---
title:               Steve Klein
tagline:             Thoughts on life, design, marketing, startups
login:               <%= ENV["obtvse_login"] ? ENV["obtvse_login"] : "username" %>
password:            <%= ENV["obtvse_password"] ? ENV["obtvse_password"] : "password" %>
name:                Steve Klein
twitter:             stevenklein  
github:              stevenklein
email:               stklein89@gmail.com
GA_identifier:       UA-34959654-1
disqus_shortname:    <%= ENV.fetch("disqus_shortname") { "" } %>
